// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTGlvo4zVMozAO6eyVydfkYXUhDA3nzaE',
    appId: '1:797941302742:web:844ababc724bfc6a909077',
    messagingSenderId: '797941302742',
    projectId: 'sahicheck-12d7e',
    authDomain: 'sahicheck-12d7e.firebaseapp.com',
    storageBucket: 'sahicheck-12d7e.firebasestorage.app',
    measurementId: 'G-QPZN8QX0BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJV4B-w779SlPKF9l9gShds9xPqWE0PUQ',
    appId: '1:797941302742:android:06cee0f9e7810e7f909077',
    messagingSenderId: '797941302742',
    projectId: 'sahicheck-12d7e',
    storageBucket: 'sahicheck-12d7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrRsS-eqtQ1z8sYXk2p2j41RHpAI7Sh1w',
    appId: '1:797941302742:ios:1c273a0252e9bb9f909077',
    messagingSenderId: '797941302742',
    projectId: 'sahicheck-12d7e',
    storageBucket: 'sahicheck-12d7e.firebasestorage.app',
    iosBundleId: 'com.example.sahicheckFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrRsS-eqtQ1z8sYXk2p2j41RHpAI7Sh1w',
    appId: '1:797941302742:ios:1c273a0252e9bb9f909077',
    messagingSenderId: '797941302742',
    projectId: 'sahicheck-12d7e',
    storageBucket: 'sahicheck-12d7e.firebasestorage.app',
    iosBundleId: 'com.example.sahicheckFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTGlvo4zVMozAO6eyVydfkYXUhDA3nzaE',
    appId: '1:797941302742:web:a0ff80f9c9222eec909077',
    messagingSenderId: '797941302742',
    projectId: 'sahicheck-12d7e',
    authDomain: 'sahicheck-12d7e.firebaseapp.com',
    storageBucket: 'sahicheck-12d7e.firebasestorage.app',
    measurementId: 'G-K7HQT8JGSX',
  );
}
